version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    image: tp-foyer:${TAG:-latest}
    depends_on:
      - db
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer

volumes:
  db-data: