version: '3.8'

services:
  app:
    image: tp-foyer:5.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - foyer-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - foyer-network

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonar-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8082:8081"
    networks:
      - nexus-network

volumes:
  db-data:

networks:
  foyer-network:
  sonar-network:
  nexus-network: