services:
  mysql-db:
    image: mysql:8
    container_name: mysql-tpfoyer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfoyerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tpfoyer-network

  tp-foyer-app:
    image: ikramsegni/tp-foyer-app:1.0.0
    container_name: tp-foyer-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tpfoyerdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8089:8089"  # Spring Boot app listening on 8089
    depends_on:
      - mysql-db
    networks:
      - tpfoyer-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Prometheus server
    networks:
      - tpfoyer-network
    depends_on:
      - tp-foyer-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    networks:
      - tpfoyer-network
    depends_on:
      - prometheus
