version: '3'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-tpfoyer-v2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpfoyerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # change si 3306 est déjà pris
    volumes:
      - mysql_data_v2:/var/lib/mysql
    networks:
      - tpfoyer-network-v2

  tp-foyer-app:
    image: ikramsegni/tp-foyer-app:1.0.0
    container_name: tp-foyer-app-v2
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tpfoyerdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8090:8089"
    depends_on:
      - mysql-db
    networks:
      - tpfoyer-network-v2

  prometheus:
    image: prom/prometheus
    container_name: prometheus-v2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - tpfoyer-network-v2
    depends_on:
      - tp-foyer-app

  grafana:
    image: grafana/grafana
    container_name: grafana-v2
    ports:
      - "3001:3000"
    networks:
      - tpfoyer-network-v2
    depends_on:
      - prometheus

networks:
  tpfoyer-network-v2:
    driver: bridge

volumes:
  mysql_data_v2:
    driver: local
