services:
  mysql-db:
    image: mysql:5.7
    restart: unless-stopped  # Move restart here, not under networks
    environment:
      <<: *common-env
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tpfoyerdb
      MYSQL_INNODB_FORCE_RECOVERY: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 20s  # Increased timeout
      retries: 10  # Increased retries
  
  tp-foyer:
    image: ahmed049/tp-foyer:5.0.0
    restart: on-failure  # Move restart here, not under networks
    ports:
      - "8089:8089"
    environment:
      <<: *common-env
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tpfoyerdb?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_LIQUIBASE_ENABLED: "true"
    depends_on:
      mysql-db:

volumes:
  db:
  mysql_data:
    driver: local
